spring:
  profiles:
#    分两类：一类是'dispach'，用于分发任务；另一类是'resource,...',用于接入资源
    active: resource,sample
management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
