drop table tb_resource_handle if exists;
create table tb_resource_handle (id bigint generated by default as identity, resource_type varchar(20), file_path varchar(255), file_name varchar(255), file_suffix varchar(10), file_size int, discover_time timestamp, handle_time timestamp, handler_name varchar(50), complete_time timestamp, total_success_line_num int, issue_record_file_name varchar(255), primary key (id));
drop table tb_issue_record if exists;
create table tb_issue_record (id bigint generated by default as identity, line_num int, cause varchar(255), primary key (id));
alter table tb_issue_record add constraint id_fk foreign key (id) references tb_resource_handle (id);
--drop table user if exists;
--create table user (id bigint generated by default as identity, username varchar(255), age int, primary key (id));